### ISSUE TITLE
Student Progress Tracker

### ISSUE THREAD

**Issue by DaltonMcc** [DaltonMcc/hc07-Chops#39]
- [x] set initial Progress (40 rows in progress table all set to '0' or "incomplete")
- [x] checker method to see what the 'status' of a certain rudiment ID
- [x] update method to change the status field from '0' to '1' ('1' meaning "complete")
- [x] call the setup method when a new Student "account" is created for the first time
